"""initial

Revision ID: 1986d4c5678c
Revises: None
Create Date: 2016-05-23 13:23:32.133545

"""

# revision identifiers, used by Alembic.
revision = '1986d4c5678c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('inventory_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.String(length=255), nullable=True),
    sa.Column('abc_xyz_classification', sa.String(length=2), nullable=True),
    sa.Column('standard_deviation', sa.Integer(), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('economic_order_quantity', sa.Integer(), nullable=True),
    sa.Column('demand_variability', sa.Integer(), nullable=True),
    sa.Column('average_orders', sa.Float(), nullable=True),
    sa.Column('shortages', sa.Integer(), nullable=True),
    sa.Column('excess_stock', sa.Integer(), nullable=True),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('economic_order_variable_cost', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('data_upload_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_upload_id'], ['data_upload.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_analysis')
    op.drop_table('data_upload')
    ### end Alembic commands ###
